import type { NextPage } from "next";
import Head from "next/head";
import CtaSection from "@/components/CtaSection";
import MiddleContainer from "@/components/MiddleContainer";
import TopContainer from "@/components/TopContainer";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <TopContainer />
        <MiddleContainer />
        <CtaSection />
      </main>
    </div>
  );
};

export default Home;
